apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"name":"crash-loop-pod","namespace":"default"},"spec":{"containers":[{"command":["sh","-c","exit 1"],"image":"busybox","name":"busybox"}]}}
  creationTimestamp: "2026-06-02T16:05:07Z"
  generation: 1
  name: crash-loop-pod
  namespace: default
  resourceVersion: "55458"
  uid: 76042147-2cc4-493c-bcca-4655b1b16a57
spec:
  containers:
  - command: ["sh","-c","sleep 3600"]
    image: busybox
    imagePullPolicy: Always
    name: busybox
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-sz5xz
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: cka-lab-m02
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-sz5xz
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2026-06-02T16:05:14Z"
    observedGeneration: 1
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2026-06-02T16:05:07Z"
    observedGeneration: 1
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2026-06-02T16:05:07Z"
    message: 'containers with unready status: [busybox]'
    observedGeneration: 1
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2026-06-02T16:05:07Z"
    message: 'containers with unready status: [busybox]'
    observedGeneration: 1
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2026-06-02T16:05:07Z"
    observedGeneration: 1
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://2a00ed03ebd1f5b8fa75192828294771f6332050beb6022ac3ccf8ca3daee93a
    image: busybox:latest
    imageID: docker-pullable://busybox@sha256:fd8d9aa63ba2f0982b5304e1ee8d3b90a210bc1ffb5314d980eb6962f1a9715d
    lastState:
      terminated:
        containerID: docker://2a00ed03ebd1f5b8fa75192828294771f6332050beb6022ac3ccf8ca3daee93a
        exitCode: 1
        finishedAt: "2026-06-02T16:11:18Z"
        reason: Error
        startedAt: "2026-06-02T16:11:18Z"
    name: busybox
    ready: false
    resources: {}
    restartCount: 6
    started: false
    state:
      waiting:
        message: back-off 5m0s restarting failed container=busybox pod=crash-loop-pod_default(76042147-2cc4-493c-bcca-4655b1b16a57)
        reason: CrashLoopBackOff
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-sz5xz
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 192.168.85.3
  hostIPs:
  - ip: 192.168.85.3
  observedGeneration: 1
  phase: Running
  podIP: 10.244.1.6
  podIPs:
  - ip: 10.244.1.6
  qosClass: BestEffort
  startTime: "2026-06-02T16:05:07Z"
